CREATE TABLE UTILISATEUR
(
	nom VARCHAR(20) NOT NULL,
	prenom VARCHAR(20) NOT NULL,
	login_ VARCHAR(20) PRIMARY KEY NOT NULL,
	password_ VARCHAR(20) NOT NULL
)

CREATE TABLE POKEMON
(
	ID INT PRIMARY KEY NOT NULL,
	nom VARCHAR(20) NOT NULL,
	element VARCHAR(20) NOT NULL,
	vie INT NOT NULL,
	strenght INT NOT NULL,
	agilite INT NOT NULL,
	intelligence INT NOT NULL
)

CREATE TABLE DRESSEUR
(
	ID INT PRIMARY KEY NOT NULL,
	nom VARCHAR(20) NOT NULL,
	id_pokemon INT NOT NULL FOREIGN KEY REFERENCES POKEMON(ID)
)

CREATE TABLE MATCH
(
	ID INT PRIMARY KEY NOT NULL,
	ID_pokemon1 INT FOREIGN KEY REFERENCES POKEMON(ID),
	ID_pokemon2 INT FOREIGN KEY REFERENCES POKEMON(ID),
	phase INT NOT NULL
)

CREATE TABLE STADE
(
	ID INT PRIMARY KEY NOT NULL,
	nom VARCHAR(20) NOT NULL,
	place INT NOT NULL,
	element VARCHAR(20) NOT NULL,
	vie INT NOT NULL,
	strenght INT NOT NULL,
	agilite INT NOT NULL,
	intelligence INT NOT NULL
)